ports:
- port: 8080
  onOpen: open-preview
tasks:
- init: >
    python3 -m pip install -r requirements.txt &&
    python3 manage.py migrate
  command: >
    echo "from locallibrary.settings import *" > locallibrary/local_settings.py &&
    echo "ALLOWED_HOSTS = ['*']" >> locallibrary/local_settings.py &&
    export DJANGO_SETTINGS_MODULE=locallibrary.local_settings &&
    python3 manage.py runserver 0.0.0.0:8080
github:
    prebuilds:
        pullRequestsFromForks: true

vscode:
  extensions:
    - GrapeCity.gc-excelviewer@2.1.32:Ly+iVCo1K0IFcc4V7LLvyQ==